services:
    docsmanager.webapi:
        image: ${DOCKER_REGISTRY-}docsmanagerwebapi
        build:
            context: .
            dockerfile: DocsManager.WebAPI/Dockerfile
        container_name: docsmanager_webapi
        ports:
            - "5000:5000"
        depends_on:
            - postgres
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=documents_db;Username=postgres;Password=yourpassword
            - ASPNETCORE_URLS=http://0.0.0.0:5000

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: yourpassword
            POSTGRES_DB: documents_db
        ports:
            - "5432:5432"

    frontend:
        image: nginx:latest
        container_name: frontend
        volumes:
            - ./frontend:/usr/share/nginx/html:ro
        ports:
            - "8080:80"
        depends_on:
            - docsmanager.webapi
        environment:
            - BACKEND_URL=http://docsmanager_webapi:5000
